source "https://rubygems.org"

gem 'activerecord', :require => 'active_record'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'rake'
gem 'require_all'
gem 'sqlite3', '~> 1.3.6'
gem 'pry'
gem 'colorize'
gem 'tty-table'
gem 'tty-prompt'
gem 'pastel'
gem 'tty-font'
gem 'rspec'
gem 'database_cleaner'
gem 'bcrypt', '~> 3.1.7'
